using System;
using UnityEngine;

namespace MoonshineSim.Core
{
    /// <summary>
    /// Build/version stamp for the game, surfaced at runtime.
    ///
    /// The data lives in <c>Assets/Resources/BuildInfo.json</c>, regenerated by
    /// <c>BuildVersionStamper</c> (editor) every time scripts are recompiled and
    /// on every player build. Kept as a Resources JSON asset — not a generated
    /// <c>.cs</c> file — so rewriting it never triggers another script compile.
    /// </summary>
    [Serializable]
    public sealed class BuildVersion
    {
        public const string ResourceName = "BuildInfo";

        /// <summary>Semantic version, mirrors PlayerSettings.bundleVersion (e.g. "1.0").</summary>
        public string version = "";

        /// <summary>Monotonically increasing counter — bumped on each recompile with changed sources and on each build.</summary>
        public int build = 0;

        /// <summary>Short git SHA at stamp time, or "" when git is unavailable.</summary>
        public string commit = "";

        /// <summary>git branch (or tag) at stamp time.</summary>
        public string branch = "";

        /// <summary>UTC ISO-8601 timestamp of the last stamp.</summary>
        public string builtAtUtc = "";

        /// <summary>Fingerprint of all Assets/**/*.cs used to detect "sources changed since last stamp". Internal bookkeeping.</summary>
        public string sourceHash = "";

        /// <summary>True when the last stamp was produced by a player build rather than an editor recompile.</summary>
        public bool playerBuild = false;

        private static BuildVersion _current;

        /// <summary>
        /// The current build stamp. Loaded once from Resources and cached.
        /// Falls back to a minimal stamp (just <see cref="Application.version"/>)
        /// if the asset is missing or malformed.
        /// </summary>
        public static BuildVersion Current
        {
            get
            {
                if (_current != null) return _current;

                var asset = Resources.Load<TextAsset>(ResourceName);
                if (asset != null)
                {
                    try { _current = JsonUtility.FromJson<BuildVersion>(asset.text); }
                    catch (Exception e) { Debug.LogWarning($"[BuildVersion] Could not parse {ResourceName}: {e.Message}"); }
                }

                _current ??= new BuildVersion();
                if (string.IsNullOrEmpty(_current.version)) _current.version = Application.version;
                return _current;
            }
        }

        /// <summary>Forget the cached stamp so the next access reloads it (editor use).</summary>
        public static void InvalidateCache() => _current = null;

        /// <summary>Compact one-liner for the HUD, e.g. <c>v1.0 · build 42 · a1b2c3d</c>.</summary>
        public string Short
        {
            get
            {
                string s = $"v{version} · build {build}";
                if (!string.IsNullOrEmpty(commit)) s += $" · {commit}";
                return s;
            }
        }

        /// <summary>HUD text with the build date on a second line.</summary>
        public string Long
        {
            get
            {
                string when = builtAtUtc;
                if (DateTime.TryParse(builtAtUtc, null, System.Globalization.DateTimeStyles.AdjustToUniversal, out var dt))
                    when = dt.ToString("yyyy-MM-dd HH:mm 'UTC'");

                string line1 = Short;
                if (!string.IsNullOrEmpty(branch)) line1 += $" ({branch})";
                return string.IsNullOrEmpty(when) ? line1 : $"{line1}\n{when}";
            }
        }
    }
}
